name: Serverless Cleanup on PR Close
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
on:
  # pull_request:
  #   types: [closed]
  workflow_dispatch:

# Specify what jobs to run
jobs:
  CleanUp:
    name: Cleanup Feature Branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          BRANCH="$(echo ${{ github.event.pull_request.head.ref}} | sed 's/\//-/g')"
          BRANCH="${BRANCH,,}"
          echo "BRANCH is $BRANCH"
          echo "STAGE=$BRANCH" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{vars.DEV_SBX_DEPLOY_ROLE}}
          role-session-name: serverless-python-demo
          aws-region: us-east-2

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Serverless/Plugins
        run: npm ci

      - name: Serverless Remove
        run: npx serverless remove --stage $STAGE